version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/patcher"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/patcher/upstream"
    schedule:
      interval: "daily"
